module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Stitch Design System Tokens ──────────────────────────
        "error":                    "#ffb4ab",
        "surface-container":        "#1f1f26",
        "surface-bright":           "#393840",
        "tertiary-container":       "#00a74b",
        "tertiary-fixed-dim":       "#4ae176",
        "surface-dim":              "#131319",
        "outline-variant":          "#424754",
        "inverse-primary":          "#005ac2",
        "primary":                  "#adc6ff",
        "on-error":                 "#690005",
        "on-secondary-fixed-variant": "#5516be",
        "surface-container-high":   "#2a2930",
        "on-secondary-fixed":       "#23005c",
        "on-error-container":       "#ffdad6",
        "inverse-surface":          "#e4e1ea",
        "on-primary-fixed-variant": "#004395",
        "surface-tint":             "#adc6ff",
        "primary-container":        "#4d8eff",
        "surface-container-low":    "#1b1b21",
        "on-primary":               "#002e6a",
        "tertiary-fixed":           "#6bff8f",
        "surface":                  "#131319",
        "on-primary-container":     "#00285d",
        "surface-container-highest":"#35343b",
        "secondary-fixed":          "#e9ddff",
        "primary-fixed":            "#d8e2ff",
        "tertiary":                 "#4ae176",
        "on-tertiary":              "#003915",
        "surface-container-lowest": "#0e0e14",
        "on-secondary":             "#3c0091",
        "on-tertiary-fixed":        "#002109",
        "on-surface":               "#e4e1ea",
        "on-tertiary-fixed-variant":"#005321",
        "on-surface-variant":       "#c2c6d6",
        "primary-fixed-dim":        "#adc6ff",
        "surface-variant":          "#35343b",
        "outline":                  "#8c909f",
        "error-container":          "#93000a",
        "on-tertiary-container":    "#003111",
        "on-background":            "#e4e1ea",
        "secondary-container":      "#571bc1",
        "on-secondary-container":   "#c4abff",
        "inverse-on-surface":       "#303037",
        "background":               "#131319",
        "on-primary-fixed":         "#001a42",
        "secondary-fixed-dim":      "#d0bcff",
        "secondary":                "#d0bcff",
        // ── Legacy brand tokens (for existing components) ────────
        "brand-blue":   "#3b82f6",
        "brand-purple": "#8b5cf6",
        "brand-green":  "#22c55e",
        "brand-amber":  "#f59e0b",
        "brand-red":    "#ef4444",
      },
      fontFamily: {
        sans:           ["Inter", "system-ui", "sans-serif"],
        mono:           ["JetBrains Mono", "Fira Code", "monospace"],
        "headline-md":  ["Inter"],
        "body-lg":      ["Inter"],
        "label-caps":   ["Inter"],
        "display-lg":   ["Inter"],
        "body-md":      ["Inter"],
        "code":         ["JetBrains Mono"],
        "headline-lg":  ["Inter"],
      },
      fontSize: {
        "headline-md":  ["24px", { lineHeight: "1.3",  letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-lg":      ["16px", { lineHeight: "1.6",  fontWeight: "400" }],
        "label-caps":   ["11px", { lineHeight: "1",    letterSpacing: "0.05em",  fontWeight: "600" }],
        "display-lg":   ["48px", { lineHeight: "1.1",  letterSpacing: "-0.05em", fontWeight: "800" }],
        "body-md":      ["14px", { lineHeight: "1.5",  fontWeight: "400" }],
        "code":         ["13px", { lineHeight: "1.6",  fontWeight: "400" }],
        "headline-lg":  ["32px", { lineHeight: "1.2",  letterSpacing: "-0.025em", fontWeight: "800" }],
        // legacy
        xs:   ["0.75rem",  { lineHeight: "1rem" }],
        sm:   ["0.875rem", { lineHeight: "1.25rem" }],
        base: ["1rem",     { lineHeight: "1.5rem" }],
        lg:   ["1.125rem", { lineHeight: "1.75rem" }],
        xl:   ["1.25rem",  { lineHeight: "1.75rem" }],
        "2xl":["1.5rem",   { lineHeight: "2rem" }],
        "3xl":["1.875rem", { lineHeight: "2.25rem" }],
        "4xl":["2.25rem",  { lineHeight: "2.5rem" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
        xs:      "0.25rem",
        sm:      "0.375rem",
        base:    "0.5rem",
        "2xl":   "1.5rem",
      },
      spacing: {
        lg:             "24px",
        sm:             "8px",
        gutter:         "24px",
        base:           "4px",
        xs:             "4px",
        "container-max":"1440px",
        xl:             "40px",
        md:             "16px",
        128:            "32rem",
        144:            "36rem",
      },
      boxShadow: {
        xs:   "0 1px 2px 0 rgba(0,0,0,0.05)",
        sm:   "0 1px 2px 0 rgba(0,0,0,0.05)",
        base: "0 1px 3px 0 rgba(0,0,0,0.1),0 1px 2px 0 rgba(0,0,0,0.06)",
        md:   "0 4px 6px -1px rgba(0,0,0,0.1),0 2px 4px -1px rgba(0,0,0,0.06)",
        lg:   "0 10px 15px -3px rgba(0,0,0,0.1),0 4px 6px -2px rgba(0,0,0,0.05)",
        xl:   "0 20px 25px -5px rgba(0,0,0,0.1),0 10px 10px -5px rgba(0,0,0,0.04)",
        "glow-primary": "0 0 20px rgba(173,198,255,0.25)",
        "glow-secondary":"0 0 20px rgba(208,188,255,0.25)",
      },
      keyframes: {
        "fade-in":    { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "slide-in":   { "0%": { transform: "translateY(10px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        "pulse-ring": { "0%": { boxShadow: "0 0 0 0 rgba(173,198,255,0.7)" }, "50%": { boxShadow: "0 0 0 10px rgba(173,198,255,0)" }, "100%": { boxShadow: "0 0 0 0 rgba(173,198,255,0)" } },
        "float":      { "0%,100%": { transform: "translateY(0px)" }, "50%": { transform: "translateY(-8px)" } },
        "shimmer":    { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "stroke-dash":{ "0%": { strokeDashoffset: "301" }, "100%": { strokeDashoffset: "174" } },
      },
      animation: {
        "fade-in":    "fade-in 0.3s ease-in",
        "slide-in":   "slide-in 0.3s ease-out",
        "pulse-ring": "pulse-ring 2s infinite",
        "float":      "float 3s ease-in-out infinite",
        "shimmer":    "shimmer 1.5s infinite",
        "stroke-dash":"stroke-dash 0.8s cubic-bezier(0.4,0,0.2,1) forwards",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
  ],
};
